#!/usr/bin/env node
/* eslint-disable no-console */

/**
 * Interactive setup for the OpenRouter API key.
 *
 * Run from the frontend directory:
 *   npm run setup-key
 *
 * Prompts for an OpenRouter key, validates the format, and writes it to
 * .env.local so the browser can call the AI service. Press Enter to skip.
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");

const ENV_FILE = path.join(process.cwd(), ".env.local");
const KEY_REGEX = /^sk-or-v1-[A-Za-z0-9]{20,}$/;
const DEFAULT_MODEL = "qwen/qwen-2.5-7b-instruct:free";

function readlinePrompt(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer);
    });
  });
}

function readEnvFile() {
  if (!fs.existsSync(ENV_FILE)) return {};
  const content = fs.readFileSync(ENV_FILE, "utf8");
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    env[key] = value;
  }
  return env;
}

function writeEnvFile(env) {
  const lines = [
    "# Generated by `npm run setup-key`",
    "",
    "# OpenRouter AI (free tier) - https://openrouter.ai/keys",
    `NEXT_PUBLIC_OPENROUTER_API_KEY=${env.NEXT_PUBLIC_OPENROUTER_API_KEY || ""}`,
    `NEXT_PUBLIC_OPENROUTER_MODEL=${env.NEXT_PUBLIC_OPENROUTER_MODEL || DEFAULT_MODEL}`,
    "",
  ];
  fs.writeFileSync(ENV_FILE, lines.join("\n"), "utf8");
}

async function main() {
  console.log("\n🌾 KisanMitra AI - OpenRouter API key setup\n");
  console.log("Get your free key at: https://openrouter.ai/keys");
  console.log("(50 free requests/day on the free tier)\n");

  const answer = await readlinePrompt(
    "Enter your OpenRouter API key (or press Enter to skip): "
  );

  if (!answer.trim()) {
    console.log("\nSkipped. The voice page will use the built-in knowledge base.");
    console.log("Run `npm run setup-key` again anytime to add a key.\n");
    process.exit(0);
  }

  const key = answer.trim();
  if (!KEY_REGEX.test(key)) {
    console.log("\n❌ That doesn't look like a valid OpenRouter key.");
    console.log("Expected format: sk-or-v1-... (long alphanumeric string)");
    console.log("Get one at: https://openrouter.ai/keys\n");
    process.exit(1);
  }

  const env = readEnvFile();
  env.NEXT_PUBLIC_OPENROUTER_API_KEY = key;
  env.NEXT_PUBLIC_OPENROUTER_MODEL =
    env.NEXT_PUBLIC_OPENROUTER_MODEL || DEFAULT_MODEL;

  writeEnvFile(env);

  console.log("\n✅ Key saved to .env.local");
  console.log("⚠️  Restart the dev server (npm run dev) for changes to take effect.");
  console.log("   Then visit /voice to test the AI mode.\n");
}

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
